### ISSUE TITLE
HWC->CHW function redundancy

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/PaddleClas#194]
In operators.py
It seems that ```to_np```, ```order``` and ```channel_first``` is not necessary
we already have a ToCHWImage function

**Comment by weisy11** [comment]
Since this issue has not been updated for more than three months, it will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
It is recommended to pull and try the latest code first.
由于该问题超过三个月未更新，将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
