### ISSUE TITLE
paddleclas模型库训练的ppcls.pdparams如何转换为静态图模型参数：ppcls.pdiparams   ？

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/PaddleClas#785]
没有找到关于export_model.py的说明文档，export_model.py里面的add_argument参数中也没有关于ppcls.pdparams，那如何将训练好的动态图参数转换为静态图？我是为了之后使用opt进行转换为.nb模型然后进行推理部署。paddleclas、PaddleDetection和paddleseg的export为什么都不一样。。。但是detection和seg模型库里有关于export.py的使用文档。。。。

**Comment by Fly-hub** [comment]
找到了，哈哈哈哈，下附链接（有点隐蔽呀）：
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.1/docs/en/tutorials/getting_started_en.md
在链接中的最后面有相关介绍：
Among them, the --model parameter is used to specify the model name, --pretrained_model parameter is used to specify the model file path, the path does not need to include the model file suffix name, and --output_path is used to specify the storage path of the converted model, class_dim means number of class for the model, default as 1000.

Note:

If --output_path=./inference, then three files will be generated in the folder inference, they are inference.pdiparams, inference.pdmodel and inference.pdiparams.info.
You can specify the shape of the model input image by setting the parameter --img_size, the default is 224, which means the shape of input image is 224*224.

**Comment by weisy11** [comment]
Since this issue has not been updated for more than three months, it will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
It is recommended to pull and try the latest code first.
由于该问题超过三个月未更新，将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
