### ISSUE TITLE
自定义数据集进行训练报错：Error top4

### ISSUE THREAD

**Issue by VJoer** [PaddlePaddle/PaddleClas#846]
自定义数据集进行训练，使用resnet101，数据集有1854张图片，一共是4个类别，标签编号是0-3，请问这个报错要怎么解决？

![image](https://user-images.githubusercontent.com/41233036/122147491-94f82b00-ce8b-11eb-8bfb-224a0046e0ad.png)

![image](https://user-images.githubusercontent.com/41233036/122147461-86aa0f00-ce8b-11eb-8af2-a496d9a502d1.png)

**Comment by littletomatodonkey** [comment]
配置文件中的topk参数需要修改为一个小于4的数，比如说2，3之类的

**Comment by VJoer** [comment]
> 配置文件中的topk参数需要修改为一个小于4的数，比如说2，3之类的

好的，我试试

**Comment by VJoer** [comment]
> 配置文件中的topk参数需要修改为一个小于4的数，比如说2，3之类的

topk参数设置为3可以跑起来了，请问学习率应该样设置，我将学习率从0.1一直降低到0.000001，网络经过第一轮后loss就为nan了
![image](https://user-images.githubusercontent.com/41233036/122149368-88290680-ce8e-11eb-9c3f-fb090e14972b.png)
![image](https://user-images.githubusercontent.com/41233036/122149400-970fb900-ce8e-11eb-8589-545b980b2135.png)

**Comment by weisy11** [comment]
Since this issue has not been updated for more than three months, it will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
It is recommended to pull and try the latest code first.
由于该问题超过三个月未更新，将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
