### ISSUE TITLE
Paddle2.1 动态训练后转静态模型推理，运行出错

### ISSUE THREAD

**Issue by hi-bigcat** [PaddlePaddle/PaddleClas#855]
训练环境：Paddle 2.1
模型：EfficientB0 with se module
部署环境：Nvidia Jetson Nano，推理工具PaddlePaddle原生预测
详细信息：动态训练后模型转静态推理，在服务局上运行正常，但在Nano设备上运行出错，替换成Paddle 1.6.3的__model__后可以正常运行，error信息如下
"
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: too many resources requested for launch
Aborted (core dumped)
"

补充：原来一直使用Paddle 1.6.3训练和推理，在Nano上部署正常，更换PaddleCls 2.1训练后出现上述问题

**Comment by littletomatodonkey** [comment]
复现脚本和具体log啥的都补充下吧，这个不太能看出来

**Comment by hi-bigcat** [comment]
我们直接如流上对吧，有些隐藏信息，log文件看不出了

**Comment by JiaXiao243** [comment]
@hi-bigcat 可以具体说明一下吗？

**Comment by hi-bigcat** [comment]
问题已经解决，谢谢

**Comment by njustczr** [comment]
> 问题已经解决，谢谢

能贴一下解决方法吗？

**Comment by weisy11** [comment]
Since this issue has not been updated for more than three months, it will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
It is recommended to pull and try the latest code first.
由于该问题超过三个月未更新，将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
