### ISSUE TITLE
请问什么时候可以集成visualDL image查看?

### ISSUE THREAD

**Issue by RaidenCJ** [PaddlePaddle/PaddleClas#886]

**Comment by weisy11** [comment]
visual dl最近会有比较大的更新，我们计划在visual dl更新之后再做深入的集成

**Comment by RaidenCJ** [comment]
OK，了解~
Thanks~

**Comment by weisy11** [comment]
Since this issue has not been updated for more than three months, it will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
It is recommended to pull and try the latest code first.
由于该问题超过三个月未更新，将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
