### ISSUE TITLE
请问Aliproduct数据集如何数据清洗？

### ISSUE THREAD

**Issue by zhishao** [PaddlePaddle/PaddleClas#953]
我下载了数据集发现里面每个类别都有不少脏数据 占比还挺多的 请问这么大规模如何清洗？

**Comment by weisy11** [comment]
目前来看，只要数据集足够大，有一点脏不碍事。

**Comment by zhishao** [comment]
@weisy11 这可不是一点 我看了几个类别 脏数据占30~40还是有的

**Comment by weisy11** [comment]
分享一点经验吧，我们之前试过用一个训好模型过一遍数据，根据得分划分一个阈值，低于阈值的剔除，这样子能过滤掉很多错误的数据。这也是很多场景里面常用的过滤方法。
但是过滤了之后，指标下降了…我们分析觉得可能是把错误数据剔除的同时，一些hard的样本也被删掉了。所以，如果想要清洗，后面必须要人工再过一遍，这个数据集目前据我所知没有更好的办法。

**Comment by zhishao** [comment]
@weisy11 非常感谢  两百万张人工过一遍 这个工作量。。。

**Comment by weisy11** [comment]
Since this issue has not been updated for more than three months, it will be closed, if it is not solved or there is a follow-up one, please reopen it at any time and we will continue to follow up.
It is recommended to pull and try the latest code first.
由于该问题超过三个月未更新，将会被关闭，若问题未解决或有后续问题，请随时重新打开（建议先拉取最新代码进行尝试），我们会继续跟进。
